apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sr-chart.fullname" . }}-airflow-secrets
  labels:
    env: poc
  {{- include "sr-chart.labels" . | nindent 4 }}
data:
  sql_alchemy_conn: {{ required "airflowSecrets.sqlAlchemyConn is required" .Values.airflowSecrets.sqlAlchemyConn
    | b64enc | quote }}
type: Opaque