apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sr-chart.fullname" . }}-sr-deploy
  labels:
    env: poc
  {{- include "sr-chart.labels" . | nindent 4 }}
  annotations:
    project: sr-k8s-project
spec:
  replicas: {{ .Values.srDeploy.replicas }}
  selector:
    matchLabels:
      env: poc
    {{- include "sr-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        env: poc
      {{- include "sr-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - -c
        - while true; do sleep 600; done;
        command:
        - /bin/sh
        env:
        - name: SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              key: sql_alchemy_conn
              name: {{ include "sr-chart.fullname" . }}-airflow-secrets
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.srDeploy.nginxC1.image.repository }}:{{ .Values.srDeploy.nginxC1.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: Always
        name: nginx-c1
        ports:
        - containerPort: 80
        resources: {{- toYaml .Values.srDeploy.nginxC1.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /srdata
          name: sr-volume
      imagePullSecrets:
      - name: docker-secret
      initContainers:
      - args:
        - -c
        - echo devops code is running > /mrkp/index.html; sleep 10
        command:
        - /bin/sh
        image: busybox
        imagePullPolicy: Always
        name: busybox-c1
        resources: {}
        volumeMounts:
        - mountPath: /mrkp
          name: mrkp-volume
      nodeSelector:
        env: poc
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mrkp-volume
        persistentVolumeClaim:
          claimName: {{ include "sr-chart.fullname" . }}-sr-pvc
      - configMap:
          items:
          - key: airflow.cfg
            path: airflow.cfg
          - key: deploy.sh
            path: deploy.sh
          name: {{ include "sr-chart.fullname" . }}-airflow-configmap
        name: sr-volume