apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sr-chart.fullname" . }}-sr-job
  labels:
    env: poc
  {{- include "sr-chart.labels" . | nindent 4 }}
spec:
  backoffLimit: 2
  completions: 6
  parallelism: 2
  template:
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          chmod +x /srdata/deploy.sh
          echo "execute deploy.sh now"
        image: narendra7306/nginx:1.0
        imagePullPolicy: Always
        name: nginx-c1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-secret
      nodeSelector:
        env: poc
      restartPolicy: Never