apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "sr-chart.fullname" . }}-sr-pv
  labels:
    env: poc
  {{- include "sr-chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /ysrcp
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual